name: Test1site
favicon: null
layout_spectrum: 0.39371
typography_spectrum: 0.9856436292175204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#795c4e'
    - '#90acc1'
    - '#4788ae'
    - '#2f1822'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
