typography_spectrum: 0.3445
color:
  brandColors:
    - '#8a5937'
    - '#d56d1a'
    - '#cf906e'
    - '#fefaef'
    - '#1a0500'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44943
analytics:
  google: null
  facebook: null
  twitter: null
name: Book and other Videos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Annie And Me
    id: 5805a6fb-c70e-44a9-9af3-a140c6659a20
    type: content
  - name: Embrace Every Step
    id: fdda562e-9b7a-42c7-a11c-a96086641c0d
    type: content
favicon: null
title: Book and other Videos
purpose: []
