name: Test1site
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9856436292175204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080808'
    - '#e2d1c8'
    - '#ac9b92'
    - '#504039'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
