name: Test1site
favicon: null
layout_spectrum: 0.39371
typography_spectrum: 0.9856436292175204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d3d2'
    - '#fcfcfc'
    - '#7a7a84'
    - '#040406'
    - '#47464c'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
