name: Test1site
favicon: null
layout_spectrum: 0.39371
typography_spectrum: 0.3445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8a5937'
    - '#d56d1a'
    - '#cf906e'
    - '#fefaef'
    - '#1a0500'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
