typography_spectrum: 0.3445
color:
  brandColors:
    - '#8a5937'
    - '#d56d1a'
    - '#cf906e'
    - '#fefaef'
    - '#1a0500'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44943
analytics:
  google: UA-35516913-1
  facebook: null
  twitter: null
name: Books and Bio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Buy Books on Amazon
    url: 'https://www.amazon.com/Rich-Okun/e/B00DZO54IG/'
    type: external
  - name: Bio
    id: df29204d-8587-4ea8-90d6-5029e03801aa
    type: content
  - name: 'The Sun, The Moon, The Stars, and Maya'
    id: 0ad5f4af-9fe5-4454-8f90-abdfc66a1e76
    type: content
  - name: 'Earth, Wind, Fire And Maya'
    id: 80dc7f89-0053-4131-b29f-f2b7c9368963
    type: content
  - name: Embrace Every Step
    id: fdda562e-9b7a-42c7-a11c-a96086641c0d
    type: content
  - name: Annie And Me
    id: 5805a6fb-c70e-44a9-9af3-a140c6659a20
    type: content
favicon: null
title: Book Trailers
description: Short trailers of published books
purpose: []
