typography_spectrum: 0.3445
color:
  brandColors:
    - '#8a5937'
    - '#d56d1a'
    - '#cf906e'
    - '#fefaef'
    - '#1a0500'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44943
analytics:
  google: UA-35516913-1
  facebook: null
  twitter: null
name: Books and Bio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Empty
description: Short trailers of published books
purpose: []
